### PR TITLE
Throughput subordinate delay off master usec

### LINKED ISSUE #398: Throughput_perf should allow the user to chang subordinate_delay_off_master_usec
**Describe the bug**
Throughput_perf.exe should allow the user to change subordinate_delay_off_master_usec.

### PR DESCRIPTION
**Pull request by wes-b**
### Description of the changes:
- Added Command line option
- Fixed non-error being reported: "ERROR LibUSB transfer status of 00000000 unexpected" Where status of 0 means success.

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [ ] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [ ] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [x] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [x] Windows
- [ ] Linux

### CODE REVIEW

File: tests/throughput/throughput_perf.cpp [hunk 1]
```diff
@@ -791,6 +793,20 @@ int main(int argc, char **argv)
                 error = true;
             }
         }
+        else if (strcmp(argument, "--subordinate_delay_off_master_usec") == 0)
+        {
+            if (i + 1 <= argc)
+            {
+                g_subordinate_delay_off_master_usec = (int)strtol(argv[i + 1], NULL, 10);
```
Comment (MsDerekMa) [inline tests/throughput/throughput_perf.cpp]: This should be uint32_t to make clanghappy.
