### PR TITLE
Reset now succeeds if Color camera is hung

### LINKED ISSUE #665: AzureKinectFirmwareTool fails to reset device if color camera is hung
**Describe the bug**
AzureKinectFirmwareTool fails to reset device if color camera is hung

**To Reproduce**
1. In Device manager disable color camera
2. >AzureKinectFirmwareTool -r

**Expected behavior**
This should succeed

**Desktop (please complete the following information):**
 - SDK Version:  most resent commit

### PR DESCRIPTION
**Pull request by wes-b**
### Description of the changes:
- Allows firmware_create to succeed if only the depth MCU is found

### I tested changes on: 
- [x] Windows
- [ ] Linux

### CODE REVIEW

File: src/firmware/firmware.c [hunk 1]
```diff
@@ -162,6 +162,11 @@ k4a_result_t firmware_create(char *device_serial_number, bool resetting_device,
         if (K4A_SUCCEEDED(result))
         {
             result = TRACE_CALL(colormcu_create(container_id, &firmware->colormcu));
+            if ((resetting_device) && K4A_FAILED(result))
```
Comment (MsDerekMa) [inline src/firmware/firmware.c]: Can we double check that colormcu is not being updated if create fails/it will stay null when the create fails?

Comment (wes-b) [reply src/firmware/firmware.c]: Yes, it is NULL'd out by colormcu_create in the event of a failure. Good question
