### PR TITLE
Csharp logging

### LINKED ISSUE #488: C# should support the logging APIs
The Azure Kinect Sensor SDK supports a callbacks for logging messages. The C# API should register a callback to pipe all of the messages up into the C# layer for diagnostics and better exceptions.

### PR DESCRIPTION
**Pull request by MsDerekMa**
### Description of the changes:
- Exposes the Logging API into the C# layer so debug messages can be piped into managed code.

### Before submitting a Pull Request:
- [X] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [X] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [X] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [X] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [ ] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [X] Windows
- [ ] Linux

### CODE REVIEW

File: src/csharp/SDK/Native/NativeMethods.cs [hunk 1]
```diff
@@ -1,19 +1,22 @@
...
+// </copyright>
+//------------------------------------------------------------------------------
 using System;
 using System.Numerics;
 using System.Runtime.InteropServices;
 using System.Text;
-using Microsoft.Azure.Kinect.Sensor.Native;
 
-namespace Microsoft.Azure.Kinect.Sensor
+namespace Microsoft.Azure.Kinect.Sensor.Native
```
Comment (Brent-A) [inline src/csharp/SDK/Native/NativeMethods.cs]: Let's not move this
