### PR TITLE
Fixed x86 calling conventions in C#

### LINKED ISSUE #574: C# APIs have marshaling issues with x86
**Describe the bug**
If you attempt to run any of the C# examples using an x86 platform, they will fail with marshaling issues.

**Expected behavior**
The C# wrappers should work just fine on an x86 platform.

### PR DESCRIPTION
**Pull request by Brent-A**
### Description of the changes:
- Corrected calling convention on callback delegates.

### Before submitting a Pull Request:
- [X] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [X] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [X] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [X] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [ ] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [X] Windows
- [ ] Linux

### CODE REVIEW

File: src/csharp/SDK/Native/NativeMethods.cs [hunk 1]
```diff
@@ -199,7 +201,14 @@ public struct k4a_device_configuration_t
 
         #region Functions
 
-        [DllImport("k4a", CallingConvention = CallingConvention.Cdecl)]
+        [DllImport("k4a", CallingConvention = k4aCallingConvention)]
+        [NativeReference]
+        public static extern k4a_result_t k4a_set_allocator(
```
Comment (MsDerekMa) [inline src/csharp/SDK/Native/NativeMethods.cs]: Is this a bad merge? Why do we have two copies of k4a_set_allocator?

File: src/csharp/SDK/Native/NativeMethods.cs [hunk 2]
```diff
@@ -217,7 +226,7 @@ k4a_memory_destroy_cb_t free
             out Vector2 target_point2d,
```
Comment (MsDerekMa) [inline src/csharp/SDK/Native/NativeMethods.cs]: You missed the k4a_calibration_2d_to_2d calling convention for you Cdecl => k4aCallingConvetion.

**Comment by MsDerekMa** [comment]
You might want to update the NativeMethods in the Tests\Stubgenerator just to be complete.
