### PR TITLE
Use new firmware 1.6.104075014

### LINKED ISSUE #448: Powerline setting is changed by firmware after the camera's are started
**Describe the bug**
The power line setting for power noise (60Hz / 50Hz) is changing after starting the camera

### **REMOVE REFERENCES IN CODE TO GITHUB ISSUE 448**

**To Reproduce**
1.  Reset the device
1. call ```k4a_device_get_color_control(m_device, K4A_COLOR_CONTROL_POWERLINE_FREQUENCY, &mode, &power_setting);``` 
1. call ```k4a_device_start_cameras(m_device, &config);```
1. call ```k4a_device_get_color_control(m_device, K4A_COLOR_CONTROL_POWERLINE_FREQUENCY, &mode, &power_setting);``` 

**Expected behavior**
The powerline setting should not change

**Work Around**
Call ```k4a_device_set_color_control(m_device,                                               K4A_COLOR_CONTROL_POWERLINE_FREQUENCY,                                               K4A_COLOR_CONTROL_MODE_MANUAL, 2));``` after starting the camera's

### PR DESCRIPTION
**Pull request by wes-b**
This updates our automation to test the pending firmware in the 1.4.0 alpha package

Fixes #448, #529, #700, #784 

### Description of the changes:
- TODO's removed from tests to work around firmware issues
- New multi sync tests added

### CODE REVIEW

File: tests/multidevice/multidevice.cpp [hunk 1]
```diff
@@ -157,6 +175,258 @@ TEST_F(multidevice_ft, stream_two_2_then_1)
...
+        int64_t ts_m_c, ts_m_ir, ts_s_c, ts_s_ir;
+        k4a_image_t image_c_m, image_ir_m, image_c_s, image_ir_s;
+
+        ASSERT_EQ(K4A_RESULT_SUCCEEDED,
+                  get_syncd_captures(master, subordinate, &cap_m, &cap_s, s_config.subordinate_delay_off_master_usec));
+
+        ASSERT_NE(NULL, (int64_t)(image_c_m = k4a_capture_get_color_image(cap_m)));
+        ASSERT_NE(NULL, (int64_t)(image_c_s = k4a_capture_get_color_image(cap_s)));
+        ASSERT_NE(NULL, (int64_t)(image_ir_m = k4a_capture_get_ir_image(cap_m)));
+        ASSERT_NE(NULL, (int64_t)(image_ir_s = k4a_capture_get_ir_image(cap_s)));
```
Comment (schultetwin1) [inline tests/multidevice/multidevice.cpp]: Why do we need to cast type `k4a_image_t` to a `int64_t` here? Shouldn't this work without the cast?

File: tests/multidevice/multidevice.cpp [hunk 2]
```diff
@@ -157,6 +175,258 @@ TEST_F(multidevice_ft, stream_two_2_then_1)
...
+
+        ts_m_c = (int64_t)k4a_image_get_device_timestamp_usec(image_c_m);
+        ts_s_c = (int64_t)k4a_image_get_device_timestamp_usec(image_c_s);
+        ts_m_ir = (int64_t)k4a_image_get_device_timestamp_usec(image_ir_m);
+        ts_s_ir = (int64_t)k4a_image_get_device_timestamp_usec(image_ir_s);
```
Comment (schultetwin1) [inline tests/multidevice/multidevice.cpp]: I just realized our timestamps are in `uint64_t`, casting to `int64_t` seems unsafe. Do we need to do this?

File: tests/multidevice/multidevice.cpp [hunk 3]
```diff
@@ -157,6 +175,258 @@ TEST_F(multidevice_ft, stream_two_2_then_1)
     m_device1 = NULL;
 }
 
+#define RETURN_K4A_RESULT_LE(msg1, msg2, v1, v2)                                                                       \
+    if (!(v1 <= v2))                                                                                                   \
+    {                                                                                                                  \
+        printf("%s(%d): ERROR: expected %s <= %s\n %lld vs %lld\n", __FILE__, __LINE__, msg1, msg2, LLD(v1), LLD(v2)); \
```
[the remark this answers is not in the document]
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: PRId64 is converted to %ld in Clang and GCC, I will just stick with %lld

[the remark this answers is not in the document]
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: I see what is happening long int is 64bit, so %ld is all that is needed.

File: tests/multidevice/multidevice.cpp [hunk 4]
```diff
@@ -16,6 +16,13 @@
 // event the test regresses.
 #define WAIT_TEST_INFINITE (5 * 60 * 1000)
 
+#define LLD(val) ((long long)val)
```
[the remark this answers is not in the document]
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: static cast won't work because of the things I pass into the macro

File: tests/multidevice/multidevice.cpp [hunk 5]
```diff
@@ -157,6 +175,258 @@ TEST_F(multidevice_ft, stream_two_2_then_1)
...
+                   LLD(ts_delta));
+            k4a_capture_release(*cap_s);
+            R_EXPECT_EQ(K4A_WAIT_RESULT_SUCCEEDED, k4a_device_get_capture(sub, cap_s, 10000));
+            R_EXPECT_NE(NULL_IMAGE, (image_s = k4a_capture_get_color_image(*cap_s)));
+            ts_s = (int64_t)k4a_image_get_device_timestamp_usec(image_s);
+            ts_s_adj = ts_s - subordinate_delay_off_master_usec;
+            k4a_image_release(image_s);
+        }
+
+        ts_delta = ts_m > ts_s_adj ? ts_m - ts_s_adj : ts_s_adj - ts_m;
```
[the remark this answers is not in the document]
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: 👍

File: tests/multidevice/multidevice.cpp (hunk 1 above)
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: ASSERT_NE has some template logic to it. It doesn't like comparing NULL (int) to k4a_image_t

File: tests/multidevice/multidevice.cpp [hunk 6]
```diff
@@ -157,6 +175,258 @@ TEST_F(multidevice_ft, stream_two_2_then_1)
...
+#define R_EXPECT_EQ(v1, v2) RETURN_K4A_RESULT_EQ(#v1, #v2, v1, v2)
+#define R_EXPECT_NE(v1, v2) RETURN_K4A_RESULT_NE(#v1, #v2, v1, v2)
+
+static k4a_result_t open_master_and_subordinate(k4a_device_t *master, k4a_device_t *subordinate)
+{
+    *master = NULL;
+    *subordinate = NULL;
+
+    uint32_t devices_present = k4a_device_get_installed_count();
+    R_EXPECT_LE((int64_t)2, devices_present);
```
Comment (schultetwin1) [inline tests/multidevice/multidevice.cpp]: Another way to do this is

```suggestion
    R_EXPECT_LE(2LL, devices_present);
```

File: tests/multidevice/multidevice.cpp (hunk 2 above)
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: To do math on them they need to be signed. We should have made them signed timestamps 😞

File: tests/multidevice/multidevice.cpp (hunk 6 above)
Comment (wes-b) [reply tests/multidevice/multidevice.cpp]: Thanks!
