### PR TITLE
Fix assignment of Images to Capture objects (C#)

### LINKED ISSUE #542: Cannot create Capture in C#
**Describe the bug**

I tried to create a Capture with my own color and depth data, like this:

`

                device.StartCameras(new DeviceConfiguration
                {
                    ColorFormat = ImageFormat.ColorBGRA32,
                    ColorResolution = ColorResolution.r1080p,
                    DepthMode = DepthMode.NFOV_Unbinned,
                    SynchronizedImagesOnly = true,
                });

                using (Capture capture = Sensor.Capture.Create())
                {
                    int colorWidth = 1920, colorHeight = 1080;  // ImageFormat.ColorBGRA32
                    Image colorImage = new Image(ImageFormat.ColorBGRA32, colorWidth, colorHeight, colorWidth * 4);

                    byte[] btColorImage = new byte[colorWidth * colorHeight * 4];
                    colorImage.CopyBytesFrom(btColorImage, 0, 0, btColorImage.Length);
                    colorImage.Timestamp = new TimeSpan(DateTime.Now.Ticks);

                    int depthWidth = 640, depthHeight = 576;  // DepthMode.NFOV_Unbinned
                    Image depthImage = new Image(ImageFormat.Depth16, depthWidth, depthHeight, depthWidth * sizeof(ushort));

                    byte[] btDepthImage = new byte[depthWidth * depthHeight * sizeof(ushort)];
                    depthImage.CopyBytesFrom(btDepthImage, 0, 0, btDepthImage.Length);
                    depthImage.Timestamp = new TimeSpan(DateTime.Now.Ticks);

                    capture.Color = colorImage;
                    capture.Depth = depthImage;

                    Debug.Print("Capture.Color: " + capture.Color);  // prints null
                    Debug.Print("Capture.Depth: " + capture.Depth);  // prints null
                }
`

Although colorImage and depthImage are valid, after the assignment capture.Color and capture.Depth are both null.

**To Reproduce**

Execute the code snipped above.

**Expected behavior**

I expected to get a valid Capture with valid images inside.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: Windows 1809
 - SDK Version:  1.1.1
 - Firmware version: factory defaults  

**Additional context**

### PR DESCRIPTION
**Pull request by Brent-A**
### Description of the changes:
- Fixed issue with assignment of Image objects to Capture in C#
- Added unit tests to cover Capture class

### Before submitting a Pull Request:
- [X] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [X] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [X] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [X] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [ ] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [X] Windows
- [ ] Linux

### CODE REVIEW

File: src/csharp/SDK/Capture.cs [hunk 1]
```diff
@@ -4,8 +4,19 @@
...
 namespace Microsoft.Azure.Kinect.Sensor
 {
+    /// <summary>
+    /// A set of images captured in sync.
+    /// </summary>
     public class Capture : IDisposable
     {
+        // Image caches
+        // "Public" Images are instances available outside this class via properties.
+        // "Private" Images are instances held within this class to ensure they can't be disposed when
```
Comment (MsDerekMa) [inline src/csharp/SDK/Capture.cs]: You probably don't need the Public/Private anymore.

File: src/csharp/SDK/Capture.cs [hunk 2]
```diff
@@ -15,124 +26,116 @@ internal Capture(NativeMethods.k4a_capture_t handle)
...
+        /// Gets or sets the color image of this capture.
+        /// </summary>
+        /// <remarks>
+        /// Images assigned to this capture are owned by the Capture. When the Capture is disposed, the
+        /// Color Image will be disposed.
+        ///
+        /// By setting the Color image on a Capture, the Capture takes ownership and the Capture will
+        /// dispose the Image when the Capture is disposed.
+        ///
+        /// To get an instance of an Image that lives longer than the capture, call Image.Reference().
```
Comment (MsDerekMa) [inline src/csharp/SDK/Capture.cs]: I would add some of the xml directives like <see cref""/> to make sure the documentation knows about the links.

File: src/csharp/SDK/Capture.cs [hunk 3]
```diff
@@ -15,124 +26,116 @@ internal Capture(NativeMethods.k4a_capture_t handle)
...
-            // Lock must be held to ensure the Image in cache is not replaced while we are inspecting it
-            // It is still possible for that Image to be accessed or Disposed while this lock is held
-            lock (this)
+            get
             {
-                if (this.disposedValue)
-                {
-                    throw new ObjectDisposedException(nameof(Capture));
-                }
+                this.GetImageWrapperAndDisposePrevious(NativeMethods.k4a_capture_get_color_image, ref this.cachedColor);
```
Comment (MsDerekMa) [inline src/csharp/SDK/Capture.cs]: Why not just "return this.GetImageWrapperAndDisposePrevious"?

File: src/csharp/SDK/Capture.cs [hunk 4]
```diff
@@ -15,124 +26,116 @@ internal Capture(NativeMethods.k4a_capture_t handle)
...
             }
+
             set
+            {
+                this.SetImageWrapperAndDisposePrevious(NativeMethods.k4a_capture_set_ir_image, ref this.cachedIR, value);
+            }
+        }
+
+        /// <summary>
+        /// Gets or sets the device temperature of the capture.
```
Comment (MsDerekMa) [inline src/csharp/SDK/Capture.cs]:
```suggestion
        /// Gets or sets the device temperature at the time of the capture.
```

File: src/csharp/SDK/Capture.cs [hunk 5]
```diff
@@ -169,98 +157,235 @@ public Image Color
...
                 }
             }
         }
 
-        public float Temperature
+        /// <summary>
+        /// Creates a new capture.
+        /// </summary>
+        /// <returns>A new Capture instance.</returns>
+        public static Capture Create()
```
Comment (MsDerekMa) [inline src/csharp/SDK/Capture.cs]: What is the benefit of this class since we already have a public constructor?

File: src/csharp/SDK/Capture.cs [hunk 6]
```diff
@@ -169,98 +157,235 @@ public Image Color
...
+        /// </summary>
+        /// <param name="nativeMethod">Native method to retrieve the image.</param>
+        /// <param name="cachedImage">A cached instance of the Image that we return to callers. (Callers may dispose this image, although they shouldn't).</param>
+        /// <remarks>
+        /// If this is the first time calling the property, we construct a new wrapper.
+        /// If the handle is for an Image we have already constructed a wrapper for, we return the existing wrapper.
+        /// If the handle is for a different Image, we construct a new wrapper and dispose the old one.
+        /// If existing wrapper has been disposed, we throw an exception.
+        /// </remarks>
+        private void GetImageWrapperAndDisposePrevious(
```
Comment (MsDerekMa) [inline src/csharp/SDK/Capture.cs]: Maybe rename to UpdateCachedImage or something like that since it isn't returning an image anymore?

File: src/csharp/SDK/Capture.cs (hunk 3 above)
Comment (MsDerekMa) [reply src/csharp/SDK/Capture.cs]: Got it, didn't realize that it wasn't returning an image anymore.

File: src/csharp/SDK/Image.cs [hunk 7]
```diff
@@ -562,6 +562,34 @@ public void Dispose()
             GC.SuppressFinalize(this);
         }
 
+        /// <inheritdoc/>
+        public override bool Equals(object obj)
```
Comment (MsDerekMa) [inline src/csharp/SDK/Image.cs]: I thought you were removing the override of Equals?

File: src/csharp/Tests/UnitTests/CaptureTests.cs [hunk 8]
```diff
@@ -0,0 +1,508 @@
...
+
+            // Verify the IntPtr values directly
+            IntPtr c1_native = c1.DangerousGetHandle().DangerousGetHandle();
+            IntPtr c1_ref_native = c1_ref.DangerousGetHandle().DangerousGetHandle();
+            IntPtr c2_native = c2.DangerousGetHandle().DangerousGetHandle();
+            IntPtr c2_ref_native = c2_ref.DangerousGetHandle().DangerousGetHandle();
+
+            Assert.AreNotEqual(c1_native, c2_native);
+            Assert.AreEqual(c1_native, c1_ref_native);
+            Assert.AreEqual(c2_ref_native, c2_ref_native);
```
Comment (MsDerekMa) [inline src/csharp/Tests/UnitTests/CaptureTests.cs]:
```suggestion
            Assert.AreEqual(c2_native, c2_ref_native);
```

File: src/csharp/Tests/UnitTests/CaptureTests.cs [hunk 9]
```diff
@@ -0,0 +1,508 @@
...
+            }
+        }
+
+        private System.WeakReference CreateWithWeakReference<T>(System.Func<T> factory)
+        {
+            return new System.WeakReference(factory());
+        }
+
+        // Helper function to implement basic open/close behavior
+        private void SetOpenCloseImplementation()
```
Comment (MsDerekMa) [inline src/csharp/Tests/UnitTests/CaptureTests.cs]: Do you need this? Nothing is actually calling Device Open that I can see.

File: src/csharp/Tests/UnitTests/CaptureTests.cs [hunk 10]
```diff
@@ -0,0 +1,508 @@
...
+            // The reference to the Device object is no longer on the stack, and therefore is free to be garbage collected
+            // At this point capture.IsAlive is likely to be true, but not garanteed to be
+
+            // Force garbage collection
+            System.GC.Collect(0, System.GCCollectionMode.Forced, true);
+            System.GC.WaitForPendingFinalizers();
+
+            Assert.AreEqual(false, capture.IsAlive);
+
+            // k4a_device_close should have been called automatically
```
Comment (MsDerekMa) [inline src/csharp/Tests/UnitTests/CaptureTests.cs]:
```suggestion
            // k4a_capture_release should have been called automatically
```

File: src/csharp/Tests/UnitTests/CaptureTests.cs [hunk 11]
```diff
@@ -0,0 +1,508 @@
...
+                Capture c = Capture.Create();
+
+                // The reference should still exist and we should have not seen close called
+                Assert.AreEqual(1, count.Calls("k4a_capture_create"));
+                Assert.AreEqual(0, count.Calls("k4a_capture_release"));
+
+                return c;
+            });
+
+            // The reference to the Device object is no longer on the stack, and therefore is free to be garbage collected
```
Comment (MsDerekMa) [inline src/csharp/Tests/UnitTests/CaptureTests.cs]:
```suggestion
            // The reference to the Capture object is no longer on the stack, and therefore is free to be garbage collected
```

File: src/csharp/SDK/Capture.cs (hunk 2 above)
Comment (Brent-A) [reply src/csharp/SDK/Capture.cs]: I'm going to wait on that until we get the doxygen output going. I'd like to get a preview of what the links end up doing.

File: src/csharp/SDK/Capture.cs (hunk 5 above)
Comment (Brent-A) [reply src/csharp/SDK/Capture.cs]: I agree.

File: src/csharp/Tests/UnitTests/CaptureTests.cs (hunk 9 above)
Comment (Brent-A) [reply src/csharp/Tests/UnitTests/CaptureTests.cs]: I thought I needed it, but I guess I don't :)
